import type { PoolClient } from "pg";
import { pool } from "../db/pool";
import { SYNC_PAYLOAD_VERSION } from "../config/sync";
import type {
  SyncChangeEvent,
  SyncEntityType,
  SyncOperation,
  SyncedAttendanceSession,
  SyncedEntityPayload,
  SyncChangesBatch,
} from "../types/sync";
import { SyncFeedError } from "./syncErrors";

/**
 * The cloud's durable change feed.
 *
 * Two responsibilities live here and nothing else: append an event, and read a
 * page of the feed. Applying events is the edge's job and deliberately does not
 * exist on this side of the boundary.
 *
 * The critical design rule is that `appendChangeEvent` takes the caller's
 * `PoolClient` rather than reaching for `pool`. That is what lets a business
 * store call it from inside the transaction it already owns, so an attendance
 * session and its change event commit or roll back together. If this function
 * opened its own connection it would be a separate transaction, and a failure
 * between the two would leave the feed silently missing a committed change -
 * which the edge could never detect, because it only sees the feed.
 */

/** Batch size the provider uses when the caller does not ask for a specific one. */
export const DEFAULT_CHANGE_FEED_LIMIT = 100;

/** Hard ceiling, so one request can never ask the feed for an unbounded page. */
export const MAX_CHANGE_FEED_LIMIT = 500;

interface ChangeEventRow {
  cursor: string;
  event_id: string;
  entity_type: string;
  entity_id: string;
  operation: string;
  /**
   * Task 1 originally wrote the session payload under `session`; Task 2 generalized
   * the envelope to `entity` so a consumer can read the version before knowing the
   * type. Both are accepted on read - see `readPayload`.
   */
  payload: {
    version?: number;
    entity?: SyncedEntityPayload;
    session?: SyncedEntityPayload;
  };
  recorded_at: Date;
}

export interface AttendanceSessionEventInput {
  /** The session's `sync_id` - the identity the edge stores and upserts on. */
  syncId: string;
  cloudSessionId: number;
  cloudLecturerId: number;
  session: {
    courseOfferingId: number;
    attendanceNetworkId: number;
    locationId: number;
    courseCode: string;
    courseTitle: string;
    lecturerDisplayName: string;
    lecturerStaffId: string;
    startTime: string;
    endTime: string;
    lateThresholdMinutes: number;
    status: "ACTIVE" | "ENDED";
    endedAt: string | null;
  };
}

/**
 * Build the payload the edge will store.
 *
 * Every value needed to reconstruct the session is included so that any single
 * event is self-sufficient: the edge never has to have seen an earlier event to
 * apply a later one. That is what makes the feed replayable and what lets a gap
 * be recovered by refetching rather than by reconstructing state.
 */
function toSyncedAttendanceSession(
  input: AttendanceSessionEventInput
): SyncedAttendanceSession {
  return {
    version: SYNC_PAYLOAD_VERSION,
    syncId: input.syncId,
    cloudSessionId: input.cloudSessionId,
    cloudCourseOfferingId: input.session.courseOfferingId,
    cloudLecturerId: input.cloudLecturerId,
    cloudAttendanceNetworkId: input.session.attendanceNetworkId,
    cloudLocationId: input.session.locationId,
    courseCode: input.session.courseCode,
    courseTitle: input.session.courseTitle,
    lecturerDisplayName: input.session.lecturerDisplayName,
    lecturerStaffId: input.session.lecturerStaffId,
    startTime: input.session.startTime,
    endTime: input.session.endTime,
    lateThresholdMinutes: input.session.lateThresholdMinutes,
    status: input.session.status,
    endedAt: input.session.endedAt,
  };
}

/**
 * Append one event to the feed using the caller's transaction.
 *
 * The caller MUST already be inside a transaction on this client. There is no
 * check for that, because `pg` exposes no reliable one, and a caller that
 * forgets would get a silently non-transactional write - so the parameter is
 * required rather than optional to make that mistake visible at the call site.
 *
 * `event_id` and `cursor` are generated by the database. Letting PostgreSQL
 * assign the cursor is what guarantees it reflects row-assignment order, which
 * is the ordering the whole design depends on.
 */
export async function appendAttendanceSessionEvent(
  client: PoolClient,
  entityType: SyncEntityType,
  entityId: string,
  operation: SyncOperation,
  input: AttendanceSessionEventInput
): Promise<{ eventId: string; cursor: string }> {
  return appendChangeEvent(client, entityType, entityId, operation, {
    ...toSyncedAttendanceSession(input),
  });
}

/**
 * Append one event of any synchronized entity, using the caller's transaction.
 *
 * This is the generic form. `appendAttendanceSessionEvent` exists only because
 * attendance sessions were the first entity; new master data calls this directly
 * with its own payload.
 *
 * The payload is wrapped as `{ version, entity }` so a consumer can read the
 * version before it knows which entity it is looking at.
 */
export async function appendChangeEvent(
  client: PoolClient,
  entityType: SyncEntityType,
  entityId: string,
  operation: SyncOperation,
  payload: SyncedEntityPayload
): Promise<{ eventId: string; cursor: string }> {
  const inserted = await client.query(
    `INSERT INTO sync_change_events
       (event_id, entity_type, entity_id, operation, payload)
     VALUES (gen_random_uuid(), $1, $2, $3, $4::jsonb)
     RETURNING event_id, cursor`,
    [
      entityType,
      entityId,
      operation,
      JSON.stringify({
        version: payload.version,
        entity: payload,
      }),
    ]
  );

  const row = inserted.rows[0];
  return { eventId: row.event_id, cursor: row.cursor };
}

/**
 * Unwrap a stored payload envelope.
 *
 * Every current event carries `{ version, entity }`. Attendance-session events
 * written before Task 2 generalized the envelope carry `{ version, session }`, and
 * those rows are already in the cloud's append-only log - there is no way to
 * rewrite them. Reading only `entity` would hand those rows back as
 * `payload: undefined`, and the applier would then refuse them forever and stall
 * the cursor, so both shapes are accepted. A row with neither is a genuine
 * corruption and is surfaced as such rather than silently skipped.
 */
function readPayload(row: ChangeEventRow): SyncedEntityPayload {
  const payload = row.payload?.entity ?? row.payload?.session;
  if (!payload || typeof payload !== "object") {
    throw new SyncFeedError(
      `Sync change event ${row.event_id} at cursor ${row.cursor} carries a payload this version cannot read.`,
      false
    );
  }
  return payload;
}

/**
 * Read an ordered page of the feed strictly after `cursor`.
 *
 * One row beyond the requested limit is fetched to answer `hasMore` without a
 * second COUNT query, and then dropped. `cursor > $1 ORDER BY cursor ASC` is
 * served directly by `idx_sync_change_events_cursor`.
 */
export async function listChangeEventsSince(
  cursor: number,
  limit: number
): Promise<SyncChangesBatch> {
  const boundedLimit = Math.min(
    Math.max(1, Math.trunc(limit)),
    MAX_CHANGE_FEED_LIMIT
  );

  const result = await pool.query(
    `SELECT cursor, event_id, entity_type, entity_id, operation, payload, recorded_at
     FROM sync_change_events
     WHERE cursor > $1
     ORDER BY cursor ASC
     LIMIT $2`,
    [cursor, boundedLimit + 1]
  );

  const rows = result.rows as ChangeEventRow[];
  const hasMore = rows.length > boundedLimit;
  const page = hasMore ? rows.slice(0, boundedLimit) : rows;

  const events: SyncChangeEvent[] = page.map((row) => ({
    eventId: row.event_id,
    cursor: Number(row.cursor),
    entityType: row.entity_type as SyncChangeEvent["entityType"],
    entityId: row.entity_id,
    operation: row.operation as SyncOperation,
    payload: readPayload(row),
    recordedAt: row.recorded_at.toISOString(),
  }));

  return {
    events,
    // An empty page must not rewind the edge: it holds the cursor it asked for so
    // the worker's next poll repeats the same query.
    nextCursor: events.length > 0 ? events[events.length - 1].cursor : cursor,
    hasMore,
  };
}